In [11]:
#10.1
import numpy as np

A = np.array([[1,2,3,4],
              [1,4,9,16]])
totalRow = A.shape[0]
totalCol = A.shape[1]
A_T = np.zeros((totalCol, totalRow), dtype = int)
for row in range(totalRow):
  for col in range(totalCol):
    A_T[col][row] = A[row][col]
print(A_T)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [12]:
#10.2
import numpy as np

gram_mat = np.zeros((A_T.shape[0], A.shape[1]), dtype = int)
gramRow = gram_mat.shape[0]
gramCol = gram_mat.shape[1]
for row in range(gramRow):
  for col in range(gramCol):
    element = 0
    for x in range(A_T.shape[1]):
      multiplication = (A_T[row][x] * A[x][col])
      element += multiplication
    gram_mat[row][col] = element
print(gram_mat)

[[  2   6  12  20]
 [  6  20  42  72]
 [ 12  42  90 156]
 [ 20  72 156 272]]
